#!/bin/bash

pkill picom
pkill polybar
pkill dunst
pkill pa-applet
pkill nm-applet
pkill cava
pkill kdeconnect-indi
exec --no-startup-id compton -b -f

# Lauch daemon
sxhkd &
wmname LG3D &
feh --bg-fill /home/yuuta/Imágenes/Wallpaper/rakl4jqyplv81.png
compton --config /home/yuuta/.config/bspwm/picom.conf &
$HOME/.config/polybar/launch.sh
exec mpd &
playerctld &

#Applet
nm-applet &
pa-applet &
kdeconnect-indicator &

#Miscelaneous
setxkbmap es &

#Configurations -------------------------------#
bspc monitor -d 一 二 三 四 五 六

bspc config border_width 1
bspc config window_gap 5
bspc config split_ratio 0.50

bspc config focused_border_color "$BLUE"
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true


# Windows assignation to workspaces
bspc rule -a Termite desktop='^1' state=tiled follow=on
bspc rule -a Alacritty desktop='^1' state=tiled follow=on
bspc rule -a Nitrogen desktop='^6' state=tiled follow=on
bspc rule -a firefoxdeveloperedition desktop='^2' follow=on
bspc rule -a Opera desktop='^2'follow=on
bspc rule -a spotify desktop='^6'
bspc rule -a YouTube Music desktop='^6'
bspc rule -a Youtube desktop='^6'
bspc rule -a qtws desktop='^4' state=fullscreen follow=on
bspc rule -a Code desktop='^5'
bspc rule -a discord desktop='^6'
bspc rule -a TelegramDesktop desktop='^6'
bspc rule -a MEGAsync desktop='^4' follow=on state=floating
bspc rule -a BlueMail desktop='^4' follow=on state=floating
bspc rule -a scrcpy desktop='^4' follow=on state=floating
bspc rule -a Thunar desktop='^3'
bspc rule -a Viewnior desktop='^4' state=tiled follow=on
bspc rule -a Geany desktop='^5' state=tiled follow=on
bspc rule -a Atom desktop='^6' state=tiled follow=on
bspc rule -a Gimp desktop='^6' state=tiled follow=on
bspc rule -a Audacity desktop='^6' state=tiled follow=on
bspc rule -a Evince desktop='^5' state=tiled follow=on
bspc rule -a blender desktop='^6' state=tiled follow=on
bspc rule -a electron desktop='^4' state=tiled follow=on
bspc rule -a Thunderbird desktop='^4'


# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Enable power management
xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr

# Start bspwm scripts
bspcolors
bspcomp
bspbar
bspfloat &

# Issue Tracker (Don't Remove IT)
issue_tracker.sh
